language: generic

# Dependency of the minted package
before_install:
 - sudo apt-get install python-pygments

install:
 - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR/assignment01/doc/

script:
  - mkdir _build
  - pdflatex -interaction=nonstopmode -shell-escape -halt-on-error -output-directory _build ./main.tex
  - pdflatex -interaction=nonstopmode -shell-escape -halt-on-error -output-directory _build ./main.tex

notifications:
  email: false
