before_install:
 - sudo apt-get install python-pygments

install:
 - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_script: cd $TRAVIS_BUILD_DIR/assignment01/doc/

script:
  - texliveonfly -shell-escape ./assignment01.tex
  - texliveonfly -shell-escape ./assignment01.tex

notifications:
  email: false
