# Dependency of the minted package
before_install:
 - sudo apt-get install python-pygments

install:
 - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - mkdir _build
  - travis_wait 3 pdflatex -shell-escape -output-directory _build ./assignment01/doc/assignment01.tex
  - travis_wait 3 pdflatex -shell-escape -output-directory _build ./assignment01/doc/assignment01.tex
  - cat _build/assignment01.log

notifications:
  email: false
