sudo: required
dist: trusty
language: r

script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build assignment01/doc/assignment01.tex

notifications:
  email: false
