language: generic

# Dependency of the minted package
before_install:
 - sudo apt-get install python-pygments

install:
 - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR/assignment01/doc/

script:
  - mkdir _build
  # Prefix command with travis_wait x so it times out after 3 mins
  - travis_wait 3 pdflatex -output-directory _build ./assignment01.tex

notifications:
  email: false
