language: generic

# Dependency of the minted package
before_install:

install:
  - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
  - sudo apt-get install python-pygments

# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR/assignment01/doc/

script:
  - pfdlatex --shell-escape ./assignment01.tex

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file:
    - ./assignment01.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master

notifications:
  email: false
