language: generic

# Dependency of the minted package
before_install:
  - sudo apt-get update
  - sudo apt-get install latexmk
  - sudo apt-get install texlive-latex-extra
  - sudo apt-get install python-pygments

# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR/assignment01/doc/

script:
  - latexmk -pdf -shell-escape -interaction=nonstopmode

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file:
    - ./assignment01.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master

notifications:
  email: false
