# Dependency of the minted package
before_install:
 - sudo apt-get install python-pygments

install:
 - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - texliveonfly -shell-escape ./assignment01/doc/assignment01.tex
  - texliveonfly -shell-escape ./assignment01/doc/assignment01.tex

notifications:
  email: false
